//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiak.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incluye
    {
        public int CodigoF { get; set; }
        public int CodS { get; set; }
        public Nullable<int> coste { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
